# Stage 1 - the build process
FROM node:16-alpine as build

WORKDIR /app

USER root

ENV PATH /app/node_modules/.bin:$PATH

COPY .npmrc .npmrc
COPY .env.production ./
COPY package.json ./
COPY package-lock.json ./

RUN npm ci
RUN npm install react-scripts@4.0.3 -g --silent

COPY . ./

RUN npm run build

# Stage 2 - the production environment
FROM nginx:1.21.1-alpine

COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html

RUN chown -R root:nginx /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]