FROM node:16-alpine

RUN apk add --update --no-cache g++ make python3 && ln -sf python3 /usr/bin/python

WORKDIR /service

COPY package.json ./

RUN mkdir /db

COPY ./src ./src

RUN npm install --verbose

CMD ["npm", "run", "start"]
